name: multi-k8s-deploy
on:
  push:
    branches:
      - master

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run:  |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t sgarmendia/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true sgarmendia/react-test npm run test

      - name: Set service key
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: multi-k8s-386012

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-cluster
          location: europe-west1
      
      - name: Build
        run: |-
          docker build -t sgarmendia/multi-client:latest -t sgarmendia/multi-client:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t sgarmendia/multi-server:latest -t sgarmendia/multi-server:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t sgarmendia/multi-worker:latest -t sgarmendia/multi-worker:${{ env.SHA }} -f ./worker/Dockerfile ./worker

      - name: Push
        run: |-
          docker push sgarmendia/multi-client:latest
          docker push sgarmendia/multi-server:latest
          docker push sgarmendia/multi-worker:latest

          docker push sgarmendia/multi-client:${{ env.SHA }}
          docker push sgarmendia/multi-server:${{ env.SHA }}
          docker push sgarmendia/multi-worker:${{ env.SHA }}

      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/client-deployment client=sgarmendia/multi-client:${{ env.SHA }}
          kubectl set image deployments/server-deployment server=sgarmendia/multi-server:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=sgarmendia/multi-worker:${{ env.SHA }}





        



